version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "22:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
    - 7.2.7
    - 7.2.8
    - 7.2.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: clean-css-cli
    versions:
    - 5.1.0
    - 5.2.0
    - 5.2.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.1
  - dependency-name: bulma
    versions:
    - 0.9.1
  - dependency-name: lodash
    versions:
    - 4.17.20
